specVersion: 1.0.0
name: subquery-starter
version: 0.0.4
runner:
  node:
    name: '@subql/node'
    version: '0.33.0'
  query:
    name: '@subql/query'
    version: '0.14.0'
description: A SubQuery Project for using GraphQL Subscription
repository: 'https://github.com/tane-git/subql-subscription'
schema:
  file: ./schema.graphql
network:
  chainId: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/dictionary-polkadot'
dataSources:
  - kind: substrate/Runtime
    startBlock: 101665851
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        # - handler: handleEvent
        #   kind: substrate/EventHandler
        #   filter:
        #     module: balances
        #     method: Deposit
        # - handler: handleCall
        #   kind: substrate/CallHandler
